server:
  port: 8080

spring:
  application:
    name: admin-platform
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 113.221.57.26:8848
        enabled: true
      config:
        server-addr: 113.221.57.26:8848
        import-check:
          enabled: false
        enabled: true

jwt:
  secret-key: ${JWT_SECRET_KEY:customer-admin-jwt-secret-key-2024-auth-platform-prod}
  expiration: ${JWT_EXPIRATION:86400000}

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.company.admin.platform.**.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_uuid

logging:
  level:
    com.company.admin.platform.sys: DEBUG
    org.springframework.security: DEBUG
